<?php
include('connection.php');
require_once 'dompdf/vendor/autoload.php';

use Dompdf\Dompdf;
use Dompdf\Options;

$options = new Options();
$options->set('isHtml5ParserEnabled', true);
$options->set('isRemoteEnabled', true);

$dompdf = new Dompdf($options);
$start_date = isset($_GET['start_date']) ? $_GET['start_date'] : null;
$end_date = isset($_GET['end_date']) ? $_GET['end_date'] : null;
$sql = "SELECT * FROM transaction";
if ($start_date && $end_date) {
    $sql .= " WHERE Date_checkout BETWEEN '$start_date' AND '$end_date'";
}

$query = mysqli_query($koneksi, $sql);

if (!$query) {
    die("Query error: " . mysqli_error($koneksi));
}

$html = '<html><head>';
$html .= '<style>
            body { font-family: Arial, sans-serif; }
            .header { text-align: center; margin-bottom: 20px; }
            .header h1 { margin: 0; font-size: 24px; }
            .header h2 { margin: 0; font-size: 18px; }
            .header p { margin: 0; font-size: 12px; }
            hr { border: 1px solid #000; margin: 20px 0; }
            table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
            table, th, td { border: 1px solid #000; }
            th, td { padding: 8px; text-align: left; }
            th { background-color: #f2f2f2; }
            .footer { text-align: center; margin-top: 20px; font-size: 12px; }
          </style>';
$html .= '<script type="text/javascript">
            function triggerPrint() {
                window.print();
            }
          </script>';
$html .= '</head><body onload="triggerPrint()">';

$html .= '<div class="header">
            <h1>PT.BreakRoom Persada</h1>
            <h2>Jl.Karanglo-Lamongan, Kota Malang, Jawa Timur</h2>
            <p>Telepon: (021) 8976542456 | Email: breakroom@idn.com</p>
          </div>';
$html .= '<hr/>';
$html .= '<center><h3>Rekap Transaksi</h3></center>';
$html .= '<table>
            <tr>
                <th>No</th>
                <th>ID Transaksi</th>
                <th>ID Member</th>
                <th>ID Book</th>
                <th>Tanggal Checkout</th>
                <th>Waktu Checkout</th>
                <th>Jumlah</th>
            </tr>';

$no = 1;
while ($transaction = mysqli_fetch_array($query)) {
    $html .= "<tr>
                <td>" . $no . "</td>
                <td>" . $transaction['id_Transaction'] . "</td>
                <td>" . $transaction['id_member'] . "</td>
                <td>" . $transaction['id_trxTableBilliard'] . "</td>
                <td>" . $transaction['Date_checkout'] . "</td>
                <td>" . $transaction['Time_checkout'] . "</td>
                <td>Rp " . number_format($transaction['Amount'], 0, ',', '.') . "</td>
              </tr>";
    $no++;
}
$html .= "</table>";
$html .= '<div class="footer">Generated by BreakRoom.idn | ' . date('Y-m-d') . '</div>';
$html .= '</body></html>';

$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();
$dompdf->stream('rekap-transaksi.pdf', array("Attachment" => false));
